puts "Creating foods..."

Food.find_or_create_by!(food_name: "Almond butter")
Food.find_or_create_by!(food_name: "Almonds")
Food.find_or_create_by!(food_name: "Asparagus")
Food.find_or_create_by!(food_name: "Avocado")
Food.find_or_create_by!(food_name: "Banana")
Food.find_or_create_by!(food_name: "Broccoli rabe")
Food.find_or_create_by!(food_name: "Broccolini")
Food.find_or_create_by!(food_name: "Butternut squash")
Food.find_or_create_by!(food_name: "Carrots")
Food.find_or_create_by!(food_name: "Chia seeds")
Food.find_or_create_by!(food_name: "Chicken thighs")
Food.find_or_create_by!(food_name: "Chicken")
Food.find_or_create_by!(food_name: "Chicken/sweet potato meatballs")
Food.find_or_create_by!(food_name: "Ginger")
Food.find_or_create_by!(food_name: "Manuka honey")
Food.find_or_create_by!(food_name: "Natto")
Food.find_or_create_by!(food_name: "Pecans")
Food.find_or_create_by!(food_name: "Pepitas")
Food.find_or_create_by!(food_name: "Salmon")
Food.find_or_create_by!(food_name: "Sardines")
Food.find_or_create_by!(food_name: "Seaweed")
Food.find_or_create_by!(food_name: "Spinach")
Food.find_or_create_by!(food_name: "Sweet potato")
Food.find_or_create_by!(food_name: "Tuna")
Food.find_or_create_by!(food_name: "Turkey")
Food.find_or_create_by!(food_name: "Turmeric")
