puts "Creating food qualifiers..."

FoodQualifier.find_or_create_by!(qualifier_name: "Breast")
FoodQualifier.find_or_create_by!(qualifier_name: "Canned")
FoodQualifier.find_or_create_by!(qualifier_name: "Canned, olive oil")
FoodQualifier.find_or_create_by!(qualifier_name: "Canned, spring water")
FoodQualifier.find_or_create_by!(qualifier_name: "Dairy-free")
FoodQualifier.find_or_create_by!(qualifier_name: "Egg-free")
FoodQualifier.find_or_create_by!(qualifier_name: "Fresh")
FoodQualifier.find_or_create_by!(qualifier_name: "Fresh")
FoodQualifier.find_or_create_by!(qualifier_name: "Frozen")
FoodQualifier.find_or_create_by!(qualifier_name: "Gluten-free")
FoodQualifier.find_or_create_by!(qualifier_name: "Leg")
FoodQualifier.find_or_create_by!(qualifier_name: "Non-GMO")
FoodQualifier.find_or_create_by!(qualifier_name: "Organic")
FoodQualifier.find_or_create_by!(qualifier_name: "Raw")
FoodQualifier.find_or_create_by!(qualifier_name: "Seed oil-free")
FoodQualifier.find_or_create_by!(qualifier_name: "Thigh")
