puts "Creating medications..."

MEDICATIONS = [
  "10 ML morphine sulfate 0.5 MG/ML Injection [Duramorph]",
  "10 ML morphine sulfate 1 MG/ML Injection [Duramorph]",
  "12 HR chlorpheniramine maleate 8 MG / codeine phosphate 54.3 MG Extended Release Oral Tablet [Tuxarin]",
  "12 HR chlorpheniramine polistirex 0.8 MG/ML / codeine polistirex 4 MG/ML Extended Release Suspension [Tuzistra]",
  "20 ML morphine sulfate 10 MG/ML Injection [Infumorph]",
  "20 ML morphine sulfate 10 MG/ML Injection [Mitigo]",
  "20 ML morphine sulfate 25 MG/ML Injection [Infumorph]",
  "20 ML morphine sulfate 25 MG/ML Injection [Mitigo]",
  "Abuse-Deterrent 12 HR morphine sulfate 15 MG Extended Release Oral Tablet [Arymo]",
  "Abuse-Deterrent 12 HR morphine sulfate 30 MG Extended Release Oral Tablet [Arymo]",
  "Abuse-Deterrent 12 HR morphine sulfate 60 MG Extended Release Oral Tablet [Arymo]",
  "acetaminophen 300 MG / butalbital 50 MG / caffeine 40 MG / codeine phosphate 30 MG Oral Capsule [Fioricet with Codeine]",
  "acetaminophen 300 MG / codeine phosphate 30 MG Oral Tablet [Tylenol with Codeine]",
  "acetaminophen 300 MG / codeine phosphate 60 MG Oral Tablet [Tylenol with Codeine]",
  "aspirin 325 MG / butalbital 50 MG / caffeine 40 MG / codeine phosphate 30 MG Oral Capsule [Ascomp]",
  "brompheniramine maleate 0.266 MG/ML / codeine phosphate 1.27 MG/ML / phenylephrine hydrochloride 0.666 MG/ML Oral Solution [M-End PE]",
  "brompheniramine maleate 0.4 MG/ML / codeine phosphate 1.5 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Solution [Mar-cof BP]",
  "brompheniramine maleate 4 MG / codeine phosphate 10 MG / phenylephrine hydrochloride 10 MG Oral Tablet [Brovex PBC]",
  "brompheniramine maleate 4 MG / codeine phosphate 10 MG Oral Tablet [BroveX CB]",
  "brompheniramine maleate 4 MG / codeine phosphate 20 MG / phenylephrine hydrochloride 10 MG Oral Tablet [Brovex PBC]",
  "brompheniramine maleate 4 MG / codeine phosphate 20 MG Oral Tablet [BroveX CB]",
  "chlorcyclizine hydrochloride 2.5 MG/ML / codeine phosphate 1.8 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Solution [Statuss Green Reformulated Jan 2012]",
  "chlorpheniramine maleate 0.2 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 3 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.2 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.222 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 3.33 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.222 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.25 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 0.375 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.25 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.266 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 4 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.267 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.286 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 4.29 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.286 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.333 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 5 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.333 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.4 MG/ML / codeine phosphate 1 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Suspension [Zodryl DAC]",
  "chlorpheniramine maleate 0.4 MG/ML / codeine phosphate 1 MG/ML Oral Suspension [Zodryl AC]",
  "chlorpheniramine maleate 0.4 MG/ML / codeine phosphate 1.8 MG/ML Oral Solution [Z Tuss AC]",
  "codeine phosphate 0.5 MG/ML / guaifenesin 15 MG/ML Oral Solution [Brontex]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 3 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 3.33 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 3.75 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 4 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 4.29 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 5 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Suspension [Zodryl DEC]",
  "codeine phosphate 1.2 MG/ML / dexbrompheniramine maleate 0.133 MG/ML / pseudoephedrine hydrochloride 4 MG/ML Oral Solution [M-End Max D]",
  "codeine phosphate 1.26 MG/ML / guaifenesin 20 MG/ML Oral Solution [M-Clear WC]",
  "codeine phosphate 1.5 MG/ML / guaifenesin 45 MG/ML Oral Solution [Mar-cof CG]",
  "codeine phosphate 1.6 MG/ML / guaifenesin 40 MG/ML Oral Solution [Ninjacof XG]",
  "codeine phosphate 10 MG / guaifenesin 400 MG / pseudoephedrine hydrochloride 20 MG Oral Tablet [Ambifed-G CD]",
  "codeine phosphate 10 MG / guaifenesin 400 MG / pseudoephedrine hydrochloride 30 MG Oral Tablet [Ambifed CD]",
  "codeine phosphate 2 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Solution [Biotussin]",
  "codeine phosphate 2 MG/ML / guaifenesin 20 MG/ML / pseudoephedrine hydrochloride 6 MG/ML Oral Solution [Lortuss EX]",
  "codeine phosphate 2 MG/ML / guaifenesin 20 MG/ML Oral Solution [Cheracol with Codeine]",
  "codeine phosphate 2 MG/ML / guaifenesin 20 MG/ML Oral Solution [Cheratussin]",
  "codeine phosphate 2 MG/ML / phenylephrine hydrochloride 1 MG/ML / pyrilamine maleate 1 MG/ML Oral Solution [Zotex C]",
  "codeine phosphate 20 MG / guaifenesin 400 MG / phenylephrine hydrochloride 10 MG Oral Tablet [Maxiphen CDX]",
  "codeine phosphate 20 MG / guaifenesin 400 MG / pseudoephedrine hydrochloride 20 MG Oral Tablet [Ambifed-G CD]",
  "codeine phosphate 20 MG / guaifenesin 400 MG / pseudoephedrine hydrochloride 30 MG Oral Tablet [Ambifed CD]",
  "codeine phosphate 9 MG / guaifenesin 200 MG Oral Capsule [M-Clear WC]",
  "diazepam 10 MG Oral Tablet [Valium]",
  "diazepam 2 MG Oral Tablet [Valium]",
  "diazepam 5 MG Oral Tablet [Valium]",
  "escitalopram 10 MG Oral Tablet [Lexapro]",
  "escitalopram 20 MG Oral Tablet [Lexapro]",
  "escitalopram 5 MG Oral Tablet [Lexapro]",
  "esomeprazole 10 MG Granules for Oral Suspension [Nexium]",
  "esomeprazole 2.5 MG Granules for Oral Suspension [Nexium]",
  "esomeprazole 20 MG Delayed Release Oral Capsule [Nexium]",
  "esomeprazole 20 MG Delayed Release Oral Tablet [Nexium]",
  "esomeprazole 20 MG Granules for Oral Suspension [Nexium]",
  "esomeprazole 40 MG Delayed Release Oral Capsule [Nexium]",
  "esomeprazole 40 MG Granules for Oral Suspension [Nexium]",
  "esomeprazole 40 MG Injection [Nexium]",
  "esomeprazole 5 MG Granules for Oral Suspension [Nexium]",
  "morphine sulfate 10 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 100 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 100 MG Extended Release Oral Tablet [MS Contin]",
  "morphine sulfate 15 MG Extended Release Oral Tablet [MS Contin]",
  "morphine sulfate 20 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 200 MG Extended Release Oral Tablet [MS Contin]",
  "morphine sulfate 30 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 30 MG Extended Release Oral Tablet [MS Contin]",
  "morphine sulfate 50 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 60 MG Extended Release Oral Capsule [Kadian]",
  "morphine sulfate 60 MG Extended Release Oral Tablet [MS Contin]"
]

MEDICATIONS.each do |medication_name|
  Medication.find_or_create_by!(medication_name: medication_name)
end

puts "Medications created successfully!"
