require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_stats", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # UserStat. As you add validations to UserStat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    context "when user has no stats" do
      it "redirects to /new" do
        user = create(:user)
        user.confirm
        sign_in user
        get user_stats_url
        expect(response).to redirect_to(new_user_stat_url)
      end
    end

    context "when user has stats" do
      it "redirects to /edit" do
        user_stat = create(:user_stat)
        user_stat.user.confirm
        sign_in user_stat.user
        get user_stats_url
        expect(response).to redirect_to(edit_user_stat_url(user_stat))
      end
    end
  end

  describe "GET /show" do
    context "when user has no stats" do
      it "redirects to /new" do
        user = create(:user)
        user.confirm
        sign_in user
        get user_stat_url(1)
        expect(response).to redirect_to(new_user_stat_url)
      end
    end

    context "when user has stats" do
      it "redirects to /edit" do
        user_stat = create(:user_stat)
        user_stat.user.confirm
        sign_in user_stat.user
        get user_stat_url(user_stat)
        expect(response).to redirect_to(edit_user_stat_url(user_stat))
      end
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_stat_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_stat = UserStat.create! valid_attributes
      get edit_user_stat_url(user_stat)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserStat" do
        expect {
          post user_stats_url, params: { user_stat: valid_attributes }
        }.to change(UserStat, :count).by(1)
      end

      it "redirects to the created user_stat" do
        post user_stats_url, params: { user_stat: valid_attributes }
        expect(response).to redirect_to(user_stat_url(UserStat.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserStat" do
        expect {
          post user_stats_url, params: { user_stat: invalid_attributes }
        }.to change(UserStat, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_stats_url, params: { user_stat: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_stat" do
        user_stat = UserStat.create! valid_attributes
        patch user_stat_url(user_stat), params: { user_stat: new_attributes }
        user_stat.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_stat" do
        user_stat = UserStat.create! valid_attributes
        patch user_stat_url(user_stat), params: { user_stat: new_attributes }
        user_stat.reload
        expect(response).to redirect_to(user_stat_url(user_stat))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_stat = UserStat.create! valid_attributes
        patch user_stat_url(user_stat), params: { user_stat: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_stat" do
      user_stat = UserStat.create! valid_attributes
      expect {
        delete user_stat_url(user_stat)
      }.to change(UserStat, :count).by(-1)
    end

    it "redirects to the user_stats list" do
      user_stat = UserStat.create! valid_attributes
      delete user_stat_url(user_stat)
      expect(response).to redirect_to(user_stats_url)
    end
  end
end
